version: "3.8"

services:
  postgres:
    container_name: postgres-financeiro
    image: postgres:13

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
